name: HideRails
version: 0.4.8-SNAPSHOT
author: lulucraft321
description: Plugin for hide rails - By lulucraft321
main: fr.lulucraft321.hiderails.HideRails
load: POSTWORLD
loadbefore: [HideRails]
commands:
  hiderails:
    aliases: [hr]
    description: Main command