name: HideRails
version: 0.5.4-SNAPSHOT
author: lulucraft321
description: Plugin for hide rails, ladder, redstone, signs and iron_bars - By lulucraft321
main: fr.lulucraft321.hiderails.HideRails
load: POSTWORLD
loadbefore: [HideRails]
commands:
  hiderails:
    aliases: [hr]
    description: Main command